#!/usr/bin/env python3
"""
scripts/select_neutrino_category.py
-----------------------------------
Selects events belonging to a specific neutrino interaction category from the categorized
datasets generated by scripts/filter_neutrinos.py.

Default category:
  "muon neutrino CC interaction that creates a charm hadron that directly decays
   semileptonically with an outgoing muon, whose parent particle is that charm hadron"

Input ROOT files:
  Categorized ROOT files containing both 'cbmsim' and 'truth' trees.
Output ROOT files:
  Replaces ending '_truth.root' or '_categorized.root' with '_truth_numuCC_charmToMu.root'.

Usage:
  # Process a single partition:
  python3 scripts/select_neutrino_category.py -p 111

  # Process partitions with 10 workers in parallel:
  python3 scripts/select_neutrino_category.py -p 0-10 -j 4

  # Process all available partitions, skipping already existing outputs:
  python3 scripts/select_neutrino_category.py -j 10 --skip-existing
"""

from __future__ import annotations

import os
import sys
import time
import argparse
import traceback
from typing import List, Optional, Tuple, Dict, Any
from concurrent.futures import ProcessPoolExecutor, as_completed

_repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

import ROOT
ROOT.gROOT.SetBatch(True)

from snd import (
    load_config,
    resolve_input_files,
    extract_captures,
    derive_category_output_path,
    select_categorized_events_single_file,
)


def parse_partitions(part_arg: Optional[str]) -> Optional[List[int]]:
    """Parse partition argument like '0-400', '0,1,2', or 'all'."""
    if not part_arg or part_arg.strip().lower() == "all":
        return None

    partitions = set()
    for token in part_arg.split(","):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            parts = token.split("-")
            if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
                start, end = int(parts[0]), int(parts[1])
                for p in range(min(start, end), max(start, end) + 1):
                    partitions.add(p)
        elif token.isdigit():
            partitions.add(int(token))

    return sorted(list(partitions))


def format_partition_path(pattern: str, partition: str | int) -> str:
    """Format string pattern with partition string."""
    p_str = str(partition)
    count = pattern.count("%s")
    if count > 0:
        return pattern % tuple(p_str for _ in range(count))
    return pattern


def _run_worker_task(task_args: tuple) -> dict:
    """Worker task function executed across processes."""
    part_str, in_file, out_file, cat_cfg, truth_tree, event_tree, max_entries, write_empty, copy_meta, do_symlink = task_args
    t0 = time.time()
    try:
        res = select_categorized_events_single_file(
            input_file=in_file,
            output_file=out_file,
            cat_cfg=cat_cfg,
            truth_tree_name=truth_tree,
            event_tree_name=event_tree,
            max_entries=max_entries,
            write_empty_files=write_empty,
            copy_metadata=copy_meta,
            create_symlinks=do_symlink,
        )
        res["elapsed"] = time.time() - t0
        res["partition"] = part_str
        return res
    except Exception as e:
        traceback.print_exc()
        return {
            "partition": part_str,
            "input_file": in_file,
            "output_file": out_file,
            "status": f"error: {str(e)}",
            "total": 0,
            "processed": 0,
            "selected": 0,
            "elapsed": time.time() - t0,
        }


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Select specific neutrino interaction categories from categorized truth ROOT files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-i", "--input",
        type=str,
        default=None,
        help="Input file path or pattern (supports wildcard '*' and '%%s' placeholder)",
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help="Output file path, pattern with '%%s', or directory (optional)",
    )
    parser.add_argument(
        "-p", "--partitions",
        type=str,
        default=None,
        help="Partitions to process: range ('0-400'), comma-separated ('0,1,2'), or 'all'",
    )
    parser.add_argument(
        "-n", "--entries",
        type=int,
        default=-1,
        help="Max events per file to process (-1 for all)",
    )
    parser.add_argument(
        "-j", "--jobs",
        type=int,
        default=1,
        help="Number of parallel worker processes",
    )
    parser.add_argument(
        "-c", "--config",
        type=str,
        default=os.path.join(_repo_root, "config", "select_category_config.yaml"),
        help="Path to YAML configuration file",
    )
    parser.add_argument(
        "--category",
        type=str,
        default=None,
        help="Category name to filter (overrides config active_category)",
    )
    parser.add_argument(
        "--skip-existing",
        dest="skip_existing",
        action="store_true",
        default=False,
        help="Skip partitions where the selected ROOT file already exists and is non-empty",
    )
    parser.add_argument(
        "--no-symlinks",
        dest="create_symlinks",
        action="store_false",
        default=True,
        help="Disable creating symlinks in output partition directory",
    )
    parser.add_argument(
        "--no-empty-files",
        dest="write_empty_files",
        action="store_false",
        default=True,
        help="Do not write output ROOT files if 0 events matched the category",
    )
    return parser.parse_args()


def main():
    args = parse_arguments()

    # 1. Load Configuration
    config_path = args.config
    cfg = load_config(config_path)

    input_cfg = cfg.get("input", {})
    file_pattern = args.input if args.input is not None else input_cfg.get(
        "file_pattern",
        "/eos/user/i/idioniso/snd-numu-charm/data/%s/sndLHC.Genie-TGeant4_digCPP_categorized.root"
    )
    truth_tree_name = input_cfg.get("truth_tree_name", "truth")
    event_tree_name = input_cfg.get("event_tree_name", "cbmsim")
    max_files = input_cfg.get("max_files", -1)

    output_cfg = cfg.get("output", {})
    output_suffix = output_cfg.get("output_suffix", "_truth_numuCC_charmToMu.root")
    output_dir_override = output_cfg.get("output_dir", None)
    write_empty_files = args.write_empty_files and output_cfg.get("write_empty_files", True)
    copy_metadata = output_cfg.get("copy_metadata", True)
    create_symlinks = args.create_symlinks and output_cfg.get("create_symlinks", True)

    # 2. Resolve Category Criteria
    selection_cfg = cfg.get("selection", {})
    category_name = args.category if args.category is not None else selection_cfg.get("active_category", "numuCC_charmToMu")
    categories_dict = selection_cfg.get("categories", {})

    if category_name not in categories_dict:
        print(f"[Error] Category '{category_name}' not defined in config '{config_path}'!")
        print(f"Available categories: {list(categories_dict.keys())}")
        sys.exit(1)

    cat_cfg = categories_dict[category_name]
    cat_desc = cat_cfg.get("description", "No description provided")

    # 3. Resolve Tasks
    selected_partitions = parse_partitions(args.partitions)
    tasks: List[Tuple[str, str, str]] = []

    if selected_partitions is not None:
        for p in selected_partitions:
            in_file = format_partition_path(file_pattern, p)
            if os.path.exists(in_file):
                if args.output is not None:
                    out_file = format_partition_path(args.output, p)
                else:
                    out_file = derive_category_output_path(in_file, suffix=output_suffix, output_dir=output_dir_override)
                tasks.append((str(p), in_file, out_file))
            else:
                print(f"[Warning] Partition {p} input file not found: {in_file}")
    else:
        matched_files = resolve_input_files(file_pattern, max_files=max_files)
        for idx, in_file in enumerate(matched_files):
            captures = extract_captures(in_file, file_pattern)
            part_str = captures[0] if captures else str(idx)
            if args.output is not None:
                out_file = format_partition_path(args.output, part_str)
            else:
                out_file = derive_category_output_path(in_file, suffix=output_suffix, output_dir=output_dir_override)
            tasks.append((part_str, in_file, out_file))

    if not tasks:
        print(f"[Error] No input files found matching pattern: {file_pattern}")
        sys.exit(1)

    if args.skip_existing:
        filtered_tasks = []
        skipped_count = 0
        for p, in_f, out_f in tasks:
            if os.path.exists(out_f) and os.path.getsize(out_f) > 1024:
                skipped_count += 1
            else:
                filtered_tasks.append((p, in_f, out_f))
        print(f"[Info] --skip-existing: skipped {skipped_count} existing partition(s), {len(filtered_tasks)} remaining.")
        tasks = filtered_tasks
        if not tasks:
            print("[Info] All requested partitions already processed. Exiting.")
            return

    total_tasks = len(tasks)

    # 4. Banner
    print("=" * 80)
    print(" SND@LHC: Neutrino Event Category Selection Pipeline")
    print("=" * 80)
    print(f"Configuration file         : {config_path}")
    print(f"Input file pattern         : {file_pattern}")
    print(f"Output suffix              : {output_suffix}")
    print(f"Active category            : {category_name}")
    print(f"Category description       : {cat_desc}")
    print(f"Total partitions to process: {total_tasks}")
    print(f"Max events per partition   : {args.entries if args.entries > 0 else 'All'}")
    print(f"Parallel worker processes  : {args.jobs}")
    print(f"Write empty ROOT files     : {write_empty_files}")
    print(f"Create partition symlinks  : {create_symlinks}")
    print("=" * 80)

    # 5. Execution Loop
    start_time = time.time()
    results = []

    if args.jobs > 1 and total_tasks > 1:
        worker_args = [
            (part_str, in_f, out_f, cat_cfg, truth_tree_name, event_tree_name, args.entries, write_empty_files, copy_metadata, create_symlinks)
            for (part_str, in_f, out_f) in tasks
        ]
        print(f"\nDispatching {total_tasks} partition tasks to pool of {args.jobs} worker processes...\n")
        with ProcessPoolExecutor(max_workers=args.jobs) as executor:
            future_to_part = {
                executor.submit(_run_worker_task, w_args): w_args[0]
                for w_args in worker_args
            }
            completed_count = 0
            for future in as_completed(future_to_part):
                completed_count += 1
                res = future.result()
                results.append(res)
                p = res.get("partition", "?")
                n_sel = res.get("selected", 0)
                n_tot = res.get("total", 0)
                el = res.get("elapsed", 0.0)
                st = res.get("status", "unknown")
                print(f"[{completed_count:3d}/{total_tasks:3d}] Partition {p:<6} | {n_sel:5d}/{n_tot:5d} events selected | {el:6.1f}s | {st}")
    else:
        for idx, (part_str, in_file, out_file) in enumerate(tasks):
            print(f"\n[{idx + 1}/{total_tasks}] Processing Partition: {part_str}")
            print(f"  Input : {in_file}")
            print(f"  Output: {out_file}")

            t0 = time.time()
            res = select_categorized_events_single_file(
                input_file=in_file,
                output_file=out_file,
                cat_cfg=cat_cfg,
                truth_tree_name=truth_tree_name,
                event_tree_name=event_tree_name,
                max_entries=args.entries,
                write_empty_files=write_empty_files,
                copy_metadata=copy_metadata,
                create_symlinks=create_symlinks,
            )
            res["elapsed"] = time.time() - t0
            res["partition"] = part_str
            results.append(res)

            n_sel = res.get("selected", 0)
            n_tot = res.get("total", 0)
            el = res.get("elapsed", 0.0)
            print(f"  Selected {n_sel}/{n_tot} events in {el:.1f}s.")

    total_wall_time = time.time() - start_time

    # 6. Overall Summary
    tot_events_processed = sum(r.get("processed", 0) for r in results)
    tot_events_selected = sum(r.get("selected", 0) for r in results)
    pct_selected = (100.0 * tot_events_selected / max(tot_events_processed, 1))

    print("\n" + "=" * 80)
    print(" CATEGORY SELECTION SUMMARY")
    print("=" * 80)
    print(f"Category Name              : {category_name}")
    print(f"Category Description       : {cat_desc}")
    print(f"Total Partitions Processed : {len(results)}")
    print(f"Total Events Scanned       : {tot_events_processed}")
    print(f"Total Events Selected      : {tot_events_selected} ({pct_selected:6.2f}%)")
    print(f"Total Wall Clock Time      : {total_wall_time:.1f}s")
    print("=" * 80)
    print("\nEvent selection finished successfully!")


if __name__ == "__main__":
    main()
